export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const DATA_MEDICINE = "DATA_MEDICINE";
export const ADD_MEDICINE = "ADD_MEDICINE";
export const LOADING_MEDICINE = "LOADING_MEDICINE";
export const ERROR_MEDICINE = "ERROR_MEDICINE";
